# Generated by Django 3.2.6 on 2021-08-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
